version: "3.9"
services:
  bot:
    # build: .
    image: "${DOCKERHUB_USERNAME}/${DOCKERHUB_REPO_NAME}:padfoot_bot_latest"
    network_mode: "host"
    volumes:
      - .:/padfoot_bot_src
    ports:
      - "8443:8443"
    command: uvicorn run_bot:app --reload --port 8443 --host 0.0.0.0